import json
from pathlib import Path

DATA=Path('data')

def load(name): return json.loads((DATA/name).read_text(encoding='utf-8'))
def save(name,obj): (DATA/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def q(i,l,s,p,o,a,e,passage=None):
    x={'id':i,'level':l,'skill':s,'prompt':p,'options':o,'answer':a,'explanation':e}
    if passage is not None:x['passage']=passage
    return x

def rotate(item,target):
    opts=item.get('options'); ans=item.get('answer')
    if not isinstance(opts,list) or len(opts)!=4 or not isinstance(ans,int): return
    correct=opts[ans]; wrong=[x for n,x in enumerate(opts) if n!=ans]; out=[]
    for n in range(4): out.append(correct if n==target else wrong.pop(0))
    item['options']=out; item['answer']=target

main=load('it.json'); listening=load('it-listening.json'); speaking=load('it-speaking.json')

ADV={
'B1':[
q('it-b1-g-01','B1','grammar','Se avessi più tempo, ___ un corso serale.',['seguirei','seguivo','seguirò','ho seguito'],0,'Il periodo ipotetico della possibilità richiede congiuntivo imperfetto nella subordinata e condizionale presente nella principale.'),
q('it-b1-g-02','B1','grammar','Penso che questa soluzione ___ più semplice da applicare.',['sia','è','sarà stata','fosse ieri'],0,'Dopo un verbo di opinione non presentato come certezza si usa normalmente il congiuntivo presente.'),
q('it-b1-g-03','B1','grammar','Appena ___ il rapporto, te lo invierò.',['avrò finito','finivo','finirei','abbia finito ieri'],0,'L’azione di finire sarà completata prima di un’altra azione futura: serve il futuro anteriore.'),
q('it-b1-g-04','B1','grammar','Nonostante ___ stanco, ha continuato a lavorare.',['fosse','era','sarà','essere'],0,'La congiunzione concessiva “nonostante” introduce qui una proposizione al congiuntivo.'),
q('it-b1-g-05','B1','grammar','Mi ha chiesto se ___ disponibile il giorno seguente.',['sarei stato','sarò','sono','ero stato domani'],0,'Nel discorso indiretto al passato, un evento successivo si esprime con il condizionale composto.'),
q('it-b1-g-06','B1','grammar','Il documento deve ___ entro domani mattina.',['essere firmato','firmare','firmato essere','si firma'],0,'Dopo “deve” la forma passiva corretta è “essere firmato”.'),
q('it-b1-g-07','B1','grammar','Pur ___ poco tempo, siamo riusciti a concludere il lavoro.',['avendo','avuto','abbiamo','avremmo'],0,'“Pur avendo” è una costruzione concessiva con gerundio presente.'),
q('it-b1-g-08','B1','grammar','È la prima volta che ___ questo programma senza assistenza.',['uso','usavo','userò certamente','avrei usato'],0,'Con “è la prima volta che” e riferimento al presente è naturale il presente indicativo.'),
q('it-b1-v-09','B1','vocabulary','“Rispettare una scadenza” significa ___.',['completare il lavoro entro il termine','rinviare automaticamente il progetto','ignorare la data concordata','aumentare il budget'],0,'L’espressione indica il completamento di un’attività entro la data stabilita.'),
q('it-b1-v-10','B1','vocabulary','Una soluzione “provvisoria” è una soluzione ___.',['temporanea','definitiva','obbligatoria per legge','priva di costi'],0,'“Provvisoria” significa adottata per un periodo limitato, in attesa di una soluzione stabile.'),
q('it-b1-v-11','B1','vocabulary','“Prendere in considerazione un’osservazione” significa ___.',['valutarla prima di decidere','rifiutarla senza leggerla','pubblicarla sui social','trasformarla in un ordine'],0,'La locuzione indica che l’osservazione viene valutata come elemento utile alla decisione.'),
q('it-b1-v-12','B1','vocabulary','Se un progetto è “in ritardo”, significa che ___.',['non rispetta il calendario previsto','è stato concluso prima','non ha alcun costo','ha cambiato responsabile'],0,'Essere in ritardo significa trovarsi oltre i tempi previsti dal piano.'),
q('it-b1-v-13','B1','vocabulary','“Assumersi la responsabilità” vuol dire ___.',['accettare di rispondere delle conseguenze','delegare ogni decisione','evitare qualsiasi controllo','modificare un contratto'],0,'La locuzione indica l’accettazione delle conseguenze legate a una scelta o a un’azione.'),
q('it-b1-v-14','B1','vocabulary','Un’informazione “riservata” deve essere ___.',['protetta da accessi non autorizzati','diffusa pubblicamente','stampata in molte copie','inviata senza controllo'],0,'“Riservata” indica un’informazione destinata solo a persone autorizzate.'),
q('it-b1-r-15','B1','reading','Perché l’azienda non introdurrà subito il nuovo sistema in tutti i reparti?',['Vuole prima verificarne il funzionamento in un’area limitata','Non dispone di alcun computer','Il sistema è vietato','I clienti hanno annullato il progetto'],0,'Il testo descrive una fase pilota finalizzata a individuare problemi prima dell’estensione generale.','Il nuovo sistema di assistenza sarà inizialmente usato soltanto dal reparto vendite. Dopo sei settimane verranno analizzati gli errori, i tempi di risposta e i commenti degli operatori. Solo allora la direzione deciderà se estenderlo agli altri reparti.'),
q('it-b1-r-16','B1','reading','Che cosa deve fare chi non può partecipare alla prima sessione?',['Iscriversi alla data alternativa','Ignorare il corso','Presentarsi senza registrazione','Mandare un collega senza avvisare'],0,'Il messaggio prevede una seconda data per chi è impossibilitato a partecipare alla prima.','La formazione sulla sicurezza si terrà il 12 maggio. Chi quel giorno lavora fuori sede deve iscriversi alla sessione aggiuntiva del 19 maggio. La partecipazione a una delle due date è obbligatoria.'),
q('it-b1-r-17','B1','reading','Qual è il problema principale segnalato dal cliente?',['La consegna è arrivata tardi e il prodotto era danneggiato','Il prezzo era troppo basso','L’indirizzo era corretto','Il manuale era troppo lungo'],0,'Il cliente collega due problemi: il ritardo e il danno riscontrato all’apertura del pacco.','L’ordine doveva arrivare lunedì, ma il corriere lo ha consegnato soltanto giovedì. Aprendo il pacco ho notato che la scocca dell’apparecchio era crepata. Vorrei sapere se la sostituzione può avvenire senza costi aggiuntivi.'),
q('it-b1-r-18','B1','reading','Che cosa si può concludere dall’avviso?',['Alcuni servizi restano disponibili in un’altra sede','La biblioteca chiude definitivamente','Non è più possibile restituire libri','I lavori finiscono domani'],0,'L’attività è limitata, ma prestito e restituzione continuano in uno spazio temporaneo.','A causa dei lavori, la sala di lettura al primo piano resterà chiusa per due settimane. I libri potranno comunque essere presi in prestito e restituiti nel punto temporaneo dell’edificio accanto.'),
q('it-b1-r-19','B1','reading','Perché la data di inizio dei test potrebbe cambiare?',['La consegna dell’attrezzatura non è ancora confermata','Il primo periodo è finito in anticipo','Il budget è aumentato','Il cliente ha già approvato tutto'],0,'L’avvio dei test dipende da una consegna la cui data non è ancora certa.','La prima fase è terminata secondo il programma. Tuttavia aspettiamo ancora la conferma della consegna dell’attrezzatura. Se il fornitore non spedirà entro venerdì, l’inizio dei test dovrà essere rinviato.'),
q('it-b1-r-20','B1','reading','Quale decisione è stata presa dopo il sondaggio?',['Consentire due giorni di lavoro da remoto alla settimana','Eliminare completamente il lavoro da remoto','Chiudere l’ufficio','Ridurre la settimana a tre giorni'],0,'La decisione costituisce un compromesso fra le preferenze dei dipendenti e le esigenze di collaborazione.','Molti dipendenti chiedevano tre giorni di lavoro da casa, mentre i responsabili segnalavano difficoltà nella collaborazione. L’azienda ha quindi stabilito che, da giugno, sarà possibile lavorare da remoto per due giorni alla settimana.')],
'B2':[
q('it-b2-g-01','B2','grammar','Se i dati fossero stati pubblicati prima, il gruppo ___ evitare parte degli errori.',['avrebbe potuto','potrà','poteva sempre','avesse potuto'],0,'Si tratta di una conseguenza non realizzata nel passato: serve il condizionale composto.'),
q('it-b2-g-02','B2','grammar','Non è chiaro ___ la misura produrrà gli effetti annunciati.',['se','che','cui','poiché'],0,'Dopo un’espressione di incertezza si introduce una domanda indiretta con “se”.'),
q('it-b2-g-03','B2','grammar','Il rapporto è stato redatto affinché ogni ipotesi ___ verificabile.',['fosse','è','sarà','essere'],0,'La proposizione finale introdotta da “affinché” richiede il congiuntivo.'),
q('it-b2-g-04','B2','grammar','Benché la proposta ___ ragionevole, non fu approvata.',['sembrasse','sembrava','sembra','sembrerà'],0,'“Benché” introduce una concessiva al congiuntivo imperfetto, coerente con il passato.'),
q('it-b2-g-05','B2','grammar','Più le regole sono dettagliate, più diventa difficile ___ ai casi insoliti.',['adattarle','le adattavano','adattate','che adattano'],0,'Dopo “diventa difficile” serve l’infinito con il pronome oggetto: “adattarle”.'),
q('it-b2-g-06','B2','grammar','Il gruppo ha presentato varie opzioni, nessuna delle quali ___ tutti i requisiti.',['soddisfaceva','soddisfacendo','soddisfatta','avrebbe soddisfatto ieri'],0,'La relativa richiede una forma verbale finita all’imperfetto: “soddisfaceva”.'),
q('it-b2-g-07','B2','grammar','A meno che non emergano nuovi elementi, la decisione ___ invariata.',['resterà','restava','sarebbe rimasta ieri','restando'],0,'La subordinata esprime una condizione futura; nella principale è naturale il futuro semplice.'),
q('it-b2-g-08','B2','grammar','La direttrice ha escluso che il ritardo ___ da una sola causa.',['dipendesse','dipendeva','dipenderà','dipendere'],0,'Dopo “ha escluso che” riferito al passato si usa il congiuntivo imperfetto.'),
q('it-b2-v-09','B2','vocabulary','Una misura “proporzionata” è una misura ___.',['adeguata alla gravità e alla scala del problema','necessariamente più costosa','scelta senza criteri','priva di qualsiasi limite'],0,'“Proporzionata” indica un rapporto adeguato fra mezzo impiegato e problema affrontato.'),
q('it-b2-v-10','B2','vocabulary','“Corroborare un’ipotesi” significa ___.',['rafforzarla con ulteriori elementi','sostituirla con un’opinione','evitare di verificarla','renderla segreta'],0,'Il verbo indica che nuove prove o osservazioni rendono un’ipotesi più credibile.'),
q('it-b2-v-11','B2','vocabulary','Un risultato “controintuitivo” è un risultato che ___.',['contrasta con ciò che ci si aspetterebbe spontaneamente','conferma sempre il senso comune','non può essere misurato','è necessariamente falso'],0,'“Controintuitivo” descrive qualcosa che non coincide con l’aspettativa immediata.'),
q('it-b2-v-12','B2','vocabulary','“Mitigare un rischio” significa ___.',['ridurne la probabilità o l’impatto','ignorarlo completamente','trasferirlo senza valutarlo','dimostrare che non esiste'],0,'Mitigare significa limitare il rischio, non necessariamente eliminarlo.'),
q('it-b2-v-13','B2','vocabulary','Una conclusione “prematura” è formulata ___.',['prima che vi siano elementi sufficienti','dopo una verifica completa','con assoluta certezza','senza alcun riferimento temporale'],0,'“Prematura” indica una conclusione tratta troppo presto rispetto alle prove disponibili.'),
q('it-b2-v-14','B2','vocabulary','“Rendere conto di una decisione” significa ___.',['spiegarne motivi e conseguenze','annunciarla senza giustificazione','delegarla automaticamente','modificarla in segreto'],0,'La locuzione richiama responsabilità e trasparenza nella spiegazione della scelta.'),
q('it-b2-r-15','B2','reading','Quale cautela suggerisce il testo nell’interpretare il miglioramento?',['Potrebbe dipendere da un fattore eccezionale e non da una tendenza stabile','Dimostra già una crescita permanente','Rende inutile ogni confronto','Dipende certamente da un errore contabile'],0,'Il testo distingue il dato positivo dalla sua possibile spiegazione e invita a non generalizzare troppo presto.','Nel trimestre le vendite sono aumentate del dodici per cento. Tuttavia quasi metà della crescita deriva da un unico contratto straordinario, difficilmente ripetibile. Prima di parlare di inversione di tendenza sarà necessario osservare almeno altri due trimestri.'),
q('it-b2-r-16','B2','reading','Qual è il limite principale della procedura uniforme?',['Può produrre decisioni poco adatte nei casi atipici','Impedisce sempre gli errori','Elimina ogni discrezionalità positiva','Costa più di qualunque alternativa'],0,'La procedura aumenta la coerenza, ma il testo sottolinea il rischio di rigidità nei casi diversi dalla norma.','Una procedura comune riduce le differenze ingiustificate fra uffici e facilita il controllo. Nei casi insoliti, però, l’applicazione meccanica della stessa regola può ignorare circostanze rilevanti e portare a decisioni poco adeguate.'),
q('it-b2-r-17','B2','reading','Quale posizione assume l’autore sul lavoro da remoto?',['Ne riconosce benefici e costi organizzativi','Lo considera soltanto dannoso','Sostiene che non abbia prodotto cambiamenti','Propone di eliminare gli uffici'],0,'L’autore presenta un bilancio: maggiore concentrazione individuale, ma minori scambi informali.','Dopo sei mesi di lavoro ibrido, molti dipendenti riferiscono una maggiore capacità di concentrazione. Allo stesso tempo, i responsabili osservano meno scambi informali e una circolazione più lenta delle informazioni non documentate. Il risultato non è quindi univoco.'),
q('it-b2-r-18','B2','reading','Che cosa viene messo in discussione?',['L’adeguatezza dello strumento rispetto all’obiettivo','La legittimità di qualunque obiettivo','L’esistenza del problema','La competenza tecnica del personale'],0,'Il testo accetta il fine, ma dubita che il mezzo scelto sia proporzionato.','Nessuno contesta la necessità di ridurre gli abusi. Resta però da capire se il controllo generalizzato di tutte le comunicazioni sia uno strumento proporzionato o se esistano misure meno invasive e altrettanto efficaci.'),
q('it-b2-r-19','B2','reading','Perché il confronto fra i due reparti non è conclusivo?',['I reparti differiscono anche per esperienza e tipo di clienti','I dati sono stati completamente inventati','Entrambi hanno usato lo stesso sistema','Non è stata misurata alcuna prestazione'],0,'Più variabili cambiano contemporaneamente, quindi non è possibile attribuire con certezza l’effetto a una sola causa.','Il reparto che ha adottato il nuovo software ha ridotto i tempi di risposta del venti per cento. Tuttavia impiega operatori più esperti e gestisce richieste meno complesse rispetto al reparto di controllo. Il confronto suggerisce un beneficio, ma non ne prova da solo la causa.'),
q('it-b2-r-20','B2','reading','Quale soluzione propone il testo?',['Regole comuni con eccezioni motivate e verificabili','Libertà totale senza controlli','Una regola diversa per ogni persona','L’eliminazione di ogni procedura'],0,'La proposta combina coerenza generale e flessibilità controllata.','Per evitare arbitrarietà servono criteri comuni. Tuttavia le regole dovrebbero consentire deroghe nei casi realmente eccezionali, purché la decisione sia motivata, documentata e successivamente verificabile.')],
'C1':[
q('it-c1-g-01','C1','grammar','Non è tanto la quantità dei dati a contare, quanto il modo in cui essi ___.',['vengono selezionati e contestualizzati','selezionano','siano selezionando','avrebbero selezionare'],0,'La struttura correlativa richiede qui una forma passiva finita e coerente con il soggetto plurale.'),
q('it-c1-g-02','C1','grammar','Per quanto la misura ___ efficace nel breve periodo, restano dubbi sui suoi effetti strutturali.',['possa risultare','può risultare','risulterebbe ieri','risultando'],0,'“Per quanto” concessivo richiede il congiuntivo presente.'),
q('it-c1-g-03','C1','grammar','Il rapporto distingue ciò che è stato osservato da ciò che se ne ___.',['può ragionevolmente dedurre','potrà dedotto','deduceva necessariamente','sia dedurre'],0,'La costruzione impersonale con modale richiede “può … dedurre”.'),
q('it-c1-g-04','C1','grammar','Qualora ___ nuove prove, la conclusione dovrebbe essere riesaminata.',['emergessero','emergeranno','emergevano','emergendo'],0,'“Qualora” introduce una condizione ipotetica formale al congiuntivo imperfetto.'),
q('it-c1-g-05','C1','grammar','L’autore non nega il problema; contesta, semmai, che la soluzione proposta ___ l’unica possibile.',['sia','è','sarà certamente','essere'],0,'Dopo “contesta che” è richiesto il congiuntivo presente.'),
q('it-c1-g-06','C1','grammar','Aver pubblicato i criteri non implica che essi ___ comprensibili ai destinatari.',['siano diventati','sono diventati','diventeranno per forza','diventando'],0,'La subordinata oggettiva negata richiede il congiuntivo passato.'),
q('it-c1-g-07','C1','grammar','Il risultato sarebbe più convincente se il campione ___ in modo casuale.',['fosse stato selezionato','era selezionato','verrà selezionato','sia selezionando'],0,'L’ipotesi contraria al passato richiede il congiuntivo trapassato nella subordinata.'),
q('it-c1-g-08','C1','grammar','Non appena si ___ di chiarire i criteri, emersero divergenze prima invisibili.',['tentò','tentava sempre','sia tentato domani','tenterebbe'],0,'La narrazione di un evento puntuale concluso richiede il passato remoto.'),
q('it-c1-v-09','C1','vocabulary','Una tesi “circoscritta” è una tesi ___.',['limitata a condizioni e casi specifici','valida senza eccezioni','espressa in modo ambiguo','priva di qualsiasi prova'],0,'“Circoscritta” indica una portata delimitata, non universale.'),
q('it-c1-v-10','C1','vocabulary','“Esplicitare un presupposto” significa ___.',['rendere chiara un’idea implicita da cui dipende il ragionamento','eliminare tutti i dati','sostituire una prova con un’opinione','evitare di definire i termini'],0,'Esplicitare significa rendere manifesto ciò che prima era sottinteso.'),
q('it-c1-v-11','C1','vocabulary','Un’argomentazione “fallace” è ___.',['apparentemente plausibile ma logicamente difettosa','necessariamente falsa in ogni premessa','espressa con parole semplici','priva di qualunque conclusione'],0,'La fallacia riguarda il modo in cui si passa dalle premesse alla conclusione.'),
q('it-c1-v-12','C1','vocabulary','“Sottostimare un effetto” significa ___.',['valutarne l’entità come inferiore a quella reale','attribuirgli una causa certa','descriverlo con precisione','eliminarlo statisticamente'],0,'Il verbo indica una stima troppo bassa rispetto al valore effettivo.'),
q('it-c1-v-13','C1','vocabulary','Una distinzione “dirimente” è una distinzione che ___.',['risolve un punto decisivo della discussione','aggiunge un dettaglio irrilevante','rende ogni tesi equivalente','evita qualsiasi scelta'],0,'“Dirimente” indica ciò che permette di sciogliere una questione decisiva.'),
q('it-c1-v-14','C1','vocabulary','“Ridimensionare una conclusione” significa ___.',['limitarne la portata alla luce di nuovi elementi','renderla più categorica','eliminare le premesse','trasformarla in una domanda'],0,'Ridimensionare significa formulare la conclusione in modo più prudente o limitato.'),
q('it-c1-r-15','C1','reading','Qual è la principale riserva dell’autore rispetto alla trasparenza descritta?',['La pubblicazione è poco utile se i criteri decisivi restano opachi','Ogni pubblicazione di dati è dannosa','I cittadini non dovrebbero accedere ai documenti','La quantità di documenti è sempre insufficiente'],0,'La critica riguarda la qualità informativa e la comprensibilità, non la semplice quantità di materiale disponibile.','L’amministrazione ha pubblicato migliaia di pagine di documenti, ma non ha indicato quali criteri abbiano determinato la graduatoria finale. L’accesso formale alle informazioni è aumentato; la possibilità di ricostruire la decisione, invece, è rimasta quasi invariata.'),
q('it-c1-r-16','C1','reading','Che effetto hanno le obiezioni sulla tesi iniziale?',['Ne limitano la portata senza confutarla del tutto','La rendono automaticamente falsa','Non hanno alcun rapporto con la tesi','Dimostrano che i dati sono inventati'],0,'Le obiezioni impongono una formulazione più circoscritta, ma non eliminano il nucleo dell’argomento.','Le critiche mostrano che il beneficio non si verifica in ogni settore e che dipende dalla qualità dell’attuazione. Ciò non annulla l’ipotesi iniziale, ma impedisce di presentarla come una regola universale.'),
q('it-c1-r-17','C1','reading','Quale inferenza sarebbe ingiustificata?',['Estendere automaticamente il risultato a contesti diversi','Affermare che nel campione è stato osservato un effetto','Chiedere ulteriori verifiche','Distinguere osservazione e generalizzazione'],0,'Il campione può sostenere una conclusione locale, non necessariamente una generalizzazione universale.','Lo studio rileva una riduzione degli errori fra operatori volontari, già motivati e formati. Il risultato è reale per il gruppo osservato, ma non dimostra che lo stesso effetto si produrrebbe con personale scelto casualmente o in organizzazioni differenti.'),
q('it-c1-r-18','C1','reading','Quale tensione mette in evidenza il testo?',['Coerenza delle regole e sensibilità alle differenze rilevanti','Velocità e costo della connessione','Teoria linguistica e traduzione','Numero di dipendenti e dimensione degli uffici'],0,'Il testo oppone il valore dell’uniformità al rischio di ignorare differenze sostanziali.','Applicare la stessa regola a tutti rende le decisioni comparabili e riduce favoritismi. Tuttavia, quando le condizioni di partenza sono molto diverse, l’uniformità formale può produrre conseguenze sproporzionate.'),
q('it-c1-r-19','C1','reading','Perché il miglioramento osservato non dimostra da solo l’efficacia della riforma?',['Nello stesso periodo sono cambiati anche altri fattori','Il risultato è necessariamente casuale','La riforma non è mai entrata in vigore','Non esistono dati precedenti'],0,'La coincidenza temporale non basta a isolare la causa quando più condizioni mutano insieme.','Dopo la riforma i tempi di attesa sono diminuiti. Nello stesso trimestre, però, l’organico è aumentato e le richieste sono calate. Senza un confronto capace di separare questi fattori, attribuire tutto il miglioramento alla riforma sarebbe eccessivo.'),
q('it-c1-r-20','C1','reading','Quale modello decisionale sostiene il testo?',['Criteri comuni, deroghe motivate e controllo successivo','Decisioni totalmente discrezionali','Regole rigide senza eccezioni','Assenza di documentazione'],0,'La proposta combina prevedibilità, flessibilità giustificata e responsabilità.','Una buona procedura non dovrebbe scegliere fra uniformità assoluta e libertà incontrollata. Può stabilire criteri comuni, consentire eccezioni motivate e rendere ogni deroga verificabile in un controllo successivo.')],
'C2':[
q('it-c2-g-01','C2','grammar','Che la conclusione appaia plausibile non significa che le premesse da cui ___ siano sufficienti.',['discende','discenda','discenderà certamente','fosse discendere'],1,'La subordinata relativa ha valore valutativo e non assertivo; il congiuntivo “discenda” segnala tale distanza.'),
q('it-c2-g-02','C2','grammar','La misura, quand’anche ___ efficace, non risolverebbe il problema degli incentivi.',['si rivelasse','si rivela','si rivelerà','rivelandosi'],0,'“Quand’anche” introduce una concessiva ipotetica al congiuntivo imperfetto.'),
q('it-c2-g-03','C2','grammar','Non perché i dati ___ falsi, ma perché non rispondono alla domanda decisiva.',['siano','sono','saranno','essendo stati domani'],0,'La negazione di una causa presunta richiede qui il congiuntivo.'),
q('it-c2-g-04','C2','grammar','Se pure si ___ che l’effetto esiste, resterebbe da stabilirne la portata.',['ammettesse','ammetteva','ammetterà','ammettendo'],0,'“Se pure” introduce una concessione ipotetica al congiuntivo imperfetto.'),
q('it-c2-g-05','C2','grammar','La tesi è formulata in modo tale da non poter essere ___.',['confutata da alcun dato contrario','confutare','si confuta','avendo confutato'],0,'Dopo “poter essere” è richiesto il participio passato nella costruzione passiva.'),
q('it-c2-g-06','C2','grammar','A rigore, non è il risultato a essere neutrale, bensì il criterio con cui lo si ___.',['interpreta','interpretasse','sia interpretando','avrebbe interpretare'],0,'La frase definisce una proprietà generale e richiede l’indicativo presente.'),
q('it-c2-g-07','C2','grammar','Il fatto che nessuno abbia protestato non implica che tutti ___ davvero d’accordo.',['fossero','erano','saranno','essere'],0,'La subordinata dipende da una negazione dell’implicazione e richiede il congiuntivo imperfetto.'),
q('it-c2-g-08','C2','grammar','Qualunque cosa se ne ___, il compromesso non elimina il conflitto di fondo.',['dica','dice','dirà','dicendo'],0,'La costruzione concessiva indefinita richiede il congiuntivo presente.'),
q('it-c2-v-09','C2','vocabulary','Una spiegazione “ad hoc” è costruita ___.',['per salvare una tesi da un’obiezione specifica senza supporto indipendente','prima di conoscere il problema','con criteri universalmente applicabili','per semplificare il lessico'],0,'In argomentazione, “ad hoc” indica una giustificazione introdotta appositamente per evitare la confutazione.'),
q('it-c2-v-10','C2','vocabulary','“Ipostatizzare una categoria” significa ___.',['trattare un concetto astratto come se fosse una realtà autonoma','definire con precisione un termine','misurare un fenomeno direttamente','distinguere due casi empirici'],0,'Il verbo indica la trasformazione indebita di un’astrazione in un’entità considerata reale e indipendente.'),
q('it-c2-v-11','C2','vocabulary','Un criterio “autoassolutorio” è formulato in modo da ___.',['escludere preventivamente la responsabilità di chi lo applica','aumentare la possibilità di critica','rendere pubblici tutti i presupposti','separare fatti e valori'],0,'L’aggettivo descrive un criterio che tende a giustificare chi lo usa qualunque sia l’esito.'),
q('it-c2-v-12','C2','vocabulary','Una distinzione “capziosa” è ___.',['formalmente sottile ma usata per trarre in inganno','necessaria per chiarire un concetto','sostenuta da dati indipendenti','priva di implicazioni pratiche'],0,'“Capziosa” indica una distinzione apparentemente rigorosa ma orientata a ingannare o confondere.'),
q('it-c2-v-13','C2','vocabulary','“Neutralizzare un’obiezione” significa ___.',['mostrarne l’irrilevanza o assorbirla nel ragionamento','evitare di menzionarla','trasformarla in una prova contraria','accettarla senza modifiche'],0,'Neutralizzare significa impedirle di indebolire la conclusione, rispondendo al suo contenuto.'),
q('it-c2-v-14','C2','vocabulary','Un’affermazione “non falsificabile” è tale che ___.',['nessuna osservazione possibile potrebbe mostrarla falsa','è già stata dimostrata vera','usa esclusivamente dati numerici','non contiene alcun concetto astratto'],0,'Una tesi non falsificabile è protetta da qualunque possibile evidenza contraria.'),
q('it-c2-r-15','C2','reading','Qual è il problema strutturale che la riforma potrebbe lasciare intatto?',['Gli incentivi che continuano a produrre il comportamento indesiderato','La visibilità delle modifiche formali','Il numero di pagine del regolamento','La competenza grammaticale degli operatori'],0,'Il testo distingue la correzione degli effetti visibili dalla modifica delle cause che li generano.','La riforma elimina alcune pratiche manifestamente scorrette e introduce controlli più frequenti. Tuttavia i premi continuano a dipendere dagli stessi indicatori che incoraggiavano quelle pratiche. Il comportamento può quindi cambiare forma senza cambiare logica.'),
q('it-c2-r-16','C2','reading','In che senso la trasparenza può diventare una rappresentazione?',['Può mostrare un’apparenza di apertura nascondendo ciò che determina davvero la decisione','Ogni documento pubblico è falso','La pubblicazione rende impossibile ogni scelta','Le informazioni secondarie sono sempre inutili'],0,'L’apertura formale può essere usata come scena pubblica mentre criteri e passaggi decisivi restano difficili da individuare.','Un ente può pubblicare enormi quantità di materiale e dichiararsi pienamente trasparente. Se le informazioni decisive sono disperse fra dettagli secondari, l’apertura diventa però una rappresentazione: visibile come gesto, poco utile come strumento di controllo.'),
q('it-c2-r-17','C2','reading','Quale presupposto viene criticato?',['Che una regola identica produca necessariamente effetti equivalenti','Che le differenze di partenza possano essere rilevanti','Che le conseguenze debbano essere osservate','Che le decisioni abbiano bisogno di criteri'],0,'Il testo contesta l’equivalenza automatica fra uguaglianza formale e uguaglianza degli effetti.','La regola è uguale per tutti, ma richiede risorse che alcuni gruppi possiedono e altri no. Presentarla come neutrale significa assumere che condizioni di partenza differenti non modifichino gli effetti della stessa prescrizione.'),
q('it-c2-r-18','C2','reading','Perché il compromesso descritto è considerato fragile?',['Rinvia il conflitto senza chiarire quali obiettivi siano incompatibili','Raggiunge un accordo completo','Elimina ogni differenza di interesse','Rende inutili ulteriori decisioni'],0,'Il compromesso permette di agire, ma può occultare il disaccordo invece di gestirlo apertamente.','Le parti hanno scelto una formula abbastanza vaga da poter essere accettata da tutti. Proprio questa ambiguità consente l’accordo immediato, ma rinvia il momento in cui si dovrà decidere fra obiettivi che non possono essere realizzati insieme.'),
q('it-c2-r-19','C2','reading','Qual è la debolezza del ragionamento?',['Definisce il successo in modo da rendere impossibile ogni smentita','Confronta ipotesi concorrenti','Distingue risultati e intenzioni','Indica criteri verificabili prima dell’analisi'],0,'La definizione viene modificata dopo ogni esito negativo, proteggendo la tesi da qualunque prova contraria.','Quando l’indicatore migliora, il programma viene dichiarato efficace. Quando peggiora, si afferma che senza il programma il calo sarebbe stato ancora maggiore. Poiché ogni risultato conferma la stessa tesi, non è chiaro quale dato potrebbe mai smentirla.'),
q('it-c2-r-20','C2','reading','Quale distinzione è necessaria per valutare correttamente l’argomento?',['Separare dati osservati, interpretazioni e presupposti normativi','Trattare ogni interpretazione come un fatto','Ignorare le alternative','Valutare soltanto le intenzioni dichiarate'],0,'Il testo invita a distinguere livelli diversi del ragionamento per evitare che giudizi impliciti appaiano come semplici dati.','Il rapporto presenta alcune osservazioni empiriche, ma passa poi a conclusioni normative senza dichiarare i valori che guidano il passaggio. Per valutarlo occorre separare ciò che è stato misurato, l’interpretazione proposta e i criteri con cui si giudica desiderabile un esito.')]
}

keep=[x for x in main['questions'] if x['level'] in {'A1','A2'}]
for x in keep:
    c=x['options'][x['answer']]
    if len(x.get('explanation','').split())<7:
        x['explanation']=f'La risposta “{c}” rispetta la forma grammaticale o il significato richiesto dal contesto; le altre opzioni cambiano persona, tempo, genere, numero o campo semantico.'
main['questions']=keep+sum((ADV[l] for l in ['B1','B2','C1','C2']),[])
for i,x in enumerate(main['questions']): rotate(x,i%4)
main['version']='4.1.0-professional-direct'; main['questionCount']=120

LADV=[
('B1','it-b1-l-01','Allora, la riunione non comincia più alle nove. La spostiamo alle nove e trenta, ma restiamo nella stessa sala perché dopo le undici è già occupata.','Che cosa cambia davvero?',['Soltanto l’orario','La sala e il giorno','Il numero dei partecipanti','L’ordine del giorno'],0,'La persona corregge l’orario, mentre specifica che la sala resta invariata.'),
('B1','it-b1-l-02','Abbiamo esaminato il reclamo. Non faremo un rimborso immediato: sostituiremo gratuitamente il prodotto e pagheremo anche la nuova spedizione.','Quale soluzione viene proposta?',['Una sostituzione senza costi','Un rimborso parziale','Una riparazione a pagamento','Un buono per il prossimo acquisto'],0,'La soluzione comprende sostituzione gratuita e spese di spedizione a carico dell’azienda.'),
('B1','it-b1-l-03','Mandami la versione aggiornata entro giovedì, non perché la presentazione sia quel giorno, ma perché venerdì voglio controllare con calma grafici e cifre.','Perché il documento serve entro giovedì?',['Per poterlo verificare prima della presentazione','Per anticipare la presentazione','Per inviarlo al cliente giovedì sera','Per sostituire tutti i grafici'],0,'La scadenza consente una revisione il venerdì; non coincide con la data della presentazione.'),
('B1','it-b1-l-04','Il corso non è obbligatorio per tutti. Lo consigliamo soprattutto a chi usa il nuovo sistema ogni giorno; chi lo apre solo occasionalmente può consultare la guida.','A chi è rivolto soprattutto il corso?',['Agli utenti abituali del sistema','A tutti i clienti','Solo ai dirigenti','A chi non usa mai il sistema'],0,'Il consiglio riguarda chi utilizza quotidianamente il sistema.'),
('B2','it-b2-l-01','I dati del trimestre sembrano incoraggianti. Detto questo, quasi metà dell’aumento dipende da un ordine eccezionale e non ripetibile. Prima di parlare di tendenza stabile aspetterei almeno altri due periodi.','Qual è l’atteggiamento del parlante?',['Prudente, perché il miglioramento potrebbe essere temporaneo','Entusiasta, perché considera il risultato definitivo','Negativo, perché le vendite sono diminuite','Indifferente, perché i dati non contano'],0,'Il parlante riconosce il miglioramento ma ne limita la portata e chiede ulteriori osservazioni.'),
('B2','it-b2-l-02','Una procedura comune riduce le differenze arbitrarie fra uffici. Il problema è che, nei casi atipici, applicarla alla lettera può ignorare circostanze importanti. Servono quindi eccezioni motivate e controllabili.','Quale soluzione propone?',['Regole comuni con eccezioni giustificate','Una libertà totale per ogni ufficio','L’eliminazione di tutte le procedure','Una regola diversa per ogni cliente'],0,'La proposta combina uniformità generale e flessibilità documentata.'),
('B2','it-b2-l-03','Il lavoro da remoto ha migliorato la concentrazione individuale, almeno secondo il sondaggio. Però i responsabili segnalano meno scambi informali e una circolazione più lenta delle informazioni non scritte. Il bilancio, quindi, non è univoco.','Quale conclusione esprime?',['Ci sono benefici e costi organizzativi','Il lavoro remoto è soltanto positivo','Non è cambiato nulla','Gli uffici non servono più'],0,'Il parlante presenta vantaggi e svantaggi, rifiutando una valutazione unilaterale.'),
('B2','it-b2-l-04','Non mettiamo in dubbio l’obiettivo di ridurre gli abusi. La questione è se controllare tutte le comunicazioni sia davvero proporzionato, soprattutto quando esistono strumenti meno invasivi.','Che cosa viene criticato?',['L’adeguatezza del mezzo scelto','L’obiettivo della misura','L’esistenza degli abusi','La competenza del personale'],0,'Il fine è accettato; viene messa in discussione la proporzionalità dello strumento.'),
('C1','it-c1-l-01','Pubblicare più documenti può sembrare sinonimo di trasparenza. In realtà, se i criteri che determinano la decisione restano impliciti, l’abbondanza di materiale rischia persino di ostacolare il controllo. Non conta soltanto quanto viene pubblicato, ma se il percorso decisionale può essere ricostruito.','Qual è la tesi centrale?',['La trasparenza dipende dalla comprensibilità del processo, non dalla sola quantità di dati','Ogni pubblicazione rende il controllo impossibile','I criteri decisionali devono restare segreti','La quantità di documenti è sempre sufficiente'],0,'Il parlante distingue l’apertura formale dalla possibilità effettiva di comprendere la decisione.'),
('C1','it-c1-l-02','Le obiezioni mostrano che il beneficio non compare in tutti i settori e dipende dalla qualità dell’attuazione. Questo non confuta il nucleo dell’argomento, ma obbliga a formularlo con maggiore cautela e a limitarne la portata.','Che effetto hanno le obiezioni?',['Ridimensionano la tesi senza annullarla','Dimostrano che la tesi è completamente falsa','Non modificano in alcun modo l’argomento','Spostano la discussione su un altro tema'],0,'Le obiezioni restringono le condizioni di validità della conclusione.'),
('C1','it-c1-l-03','Lo studio rileva un effetto fra volontari già motivati e formati. Il risultato può essere autentico nel campione osservato, ma non dimostra che si ripeterebbe con personale scelto casualmente o in organizzazioni diverse.','Quale limite viene sottolineato?',['La generalizzazione oltre il campione è incerta','Il campione non contiene alcun dato','Il calcolo è necessariamente errato','La teoria è priva di qualunque utilità'],0,'Il parlante separa la validità locale del risultato dalla sua estensione ad altri contesti.'),
('C1','it-c1-l-04','Regole uniformi aumentano la coerenza e riducono favoritismi. Tuttavia, quando le condizioni di partenza differiscono molto, la stessa regola può produrre effetti sproporzionati. La difficoltà consiste nel mantenere criteri comuni senza ignorare differenze rilevanti.','Quale tensione emerge?',['Uniformità delle regole e adattamento ai casi','Costo e velocità della tecnologia','Teoria e pratica linguistica','Numero di documenti e dimensione degli uffici'],0,'La tensione riguarda il rapporto fra coerenza generale e sensibilità alle circostanze.'),
('C2','it-c2-l-01','La riforma elimina pratiche manifestamente scorrette, ma lascia invariati gli indicatori da cui dipendono premi e carriere. È quindi possibile che il comportamento cambi aspetto senza che cambi la logica che lo produce. Il dubbio non riguarda l’effetto immediato, bensì la causa strutturale.','Qual è il dubbio centrale?',['La riforma potrebbe non modificare gli incentivi che generano il problema','La riforma non produce alcun effetto visibile','Gli indicatori sono tecnicamente impossibili da misurare','Le pratiche precedenti erano corrette'],0,'Il parlante distingue la correzione dei sintomi dalla trasformazione degli incentivi sottostanti.'),
('C2','it-c2-l-02','Un ente può pubblicare enormi quantità di materiale e presentarsi come pienamente trasparente. Se però le informazioni decisive sono disperse fra dettagli secondari, l’apertura funziona soprattutto come rappresentazione pubblica. Formalmente tutto è disponibile; praticamente il processo resta opaco.','Che cosa significa “rappresentazione” in questo contesto?',['Un’apparenza di apertura che non rende comprensibile la decisione','Una falsificazione completa di ogni documento','Una forma teatrale priva di dati reali','Un metodo efficace per semplificare le informazioni'],0,'La trasparenza è visibile come gesto, ma poco utile come strumento di controllo.'),
('C2','it-c2-l-03','Dire che una regola è neutrale perché è identica per tutti presuppone che le differenze di partenza non ne modifichino gli effetti. Ma se rispettarla richiede risorse distribuite in modo diseguale, l’uniformità formale può consolidare, anziché ridurre, uno squilibrio.','Quale presupposto viene criticato?',['Che una regola identica produca necessariamente effetti equivalenti','Che le condizioni iniziali possano essere diverse','Che le conseguenze vadano osservate empiricamente','Che una regola debba essere formulata chiaramente'],0,'Il parlante contesta l’equivalenza automatica fra identità della regola e neutralità degli effetti.'),
('C2','it-c2-l-04','Il compromesso consente di decidere senza un accordo completo, ma diventa fragile quando la formula comune è abbastanza vaga da nascondere obiettivi incompatibili. In quel caso il conflitto non viene risolto: viene soltanto rinviato al momento dell’attuazione.','Perché il compromesso è fragile?',['Occulta il conflitto invece di chiarirlo','Raggiunge un accordo troppo dettagliato','Elimina ogni differenza di interesse','Impedisce qualunque decisione immediata'],0,'La vaghezza rende possibile l’accordo iniziale, ma rinvia il conflitto sostanziale.')]
keepL=[x for x in listening['questions'] if x['level'] in {'A1','A2'}]
for x in keepL:
    c=x['options'][x['answer']]
    x['explanation']=f'Nell’audio viene fornita l’informazione che porta a “{c}”. Le altre opzioni cambiano orario, luogo, quantità o azione.'
listening['questions']=keepL+[{'id':i,'level':l,'skill':'listening','transcript':t,'prompt':p,'options':o,'answer':a,'maxPlays':2,'explanation':e} for l,i,t,p,o,a,e in LADV]
for i,x in enumerate(listening['questions']): rotate(x,(i*3+1)%4)
listening['version']='4.1.0-professional-direct'; listening['questionCount']=40

S=[
('B1','it-b1-s-01','A causa di un guasto tecnico, la formazione inizierà trenta minuti più tardi. Avvisate anche i colleghi che stanno raggiungendo l’ufficio e controllate l’aggiornamento nel calendario condiviso.',70),
('B1','it-b1-s-02','Il cliente ha ricevuto il pacco nei tempi previsti, ma due articoli erano danneggiati. Verificheremo le fotografie, contatteremo il corriere e proporremo una soluzione entro domani pomeriggio.',70),
('B1','it-b1-s-03','Se non può presentarsi all’appuntamento, lo annulli almeno ventiquattro ore prima. In caso contrario potrebbe essere applicata una tariffa, salvo situazioni eccezionali debitamente documentate.',70),
('B1','it-b1-s-04','L’orario flessibile facilita la vita quotidiana, ma il gruppo ha bisogno di regole chiare per condividere informazioni, responsabilità e scadenze senza creare incomprensioni.',70),
('B2','it-b2-s-01','L’introduzione del nuovo sistema è stata rinviata perché alcune integrazioni non funzionano ancora in modo affidabile. Prima del lancio svolgeremo un’altra fase di prova, controlleremo i dati trasferiti e verificheremo che gli operatori sappiano gestire anche le eccezioni.',95),
('B2','it-b2-s-02','I risultati indicano un miglioramento, ma una parte rilevante della crescita dipende da un ordine eccezionale. Prima di parlare di una svolta stabile sarà necessario confrontare più trimestri e distinguere gli effetti temporanei dai cambiamenti strutturali.',95),
('B2','it-b2-s-03','Valutare attentamente i rischi non significa rallentare ogni decisione. Una verifica iniziale può evitare errori costosi, chiarire le responsabilità e rendere più semplice correggere il progetto prima che venga esteso a tutta l’organizzazione.',95),
('B2','it-b2-s-04','Il reclamo non riguarda soltanto il ritardo, ma soprattutto la mancanza di comunicazione chiara. Il cliente avrebbe accettato un rinvio ragionevole, purché fosse stato informato tempestivamente e avesse ricevuto indicazioni coerenti.',95),
('C1','it-c1-s-01','Una maggiore quantità di dati non garantisce automaticamente più obiettività. Contano il modo in cui le informazioni sono raccolte, i criteri con cui vengono selezionate e il contesto nel quale vengono interpretate. Senza queste precisazioni, una presentazione apparentemente neutrale può orientare il lettore in modo invisibile.',110),
('C1','it-c1-s-02','Le obiezioni sono comprensibili e meritano una risposta puntuale, ma non annullano necessariamente la conclusione principale. Possono invece limitarne la portata, chiarire le condizioni in cui vale e impedire che un risultato circoscritto venga trasformato in una regola universale.',110),
('C1','it-c1-s-03','La trasparenza non dipende dal numero di documenti pubblicati, bensì dalla possibilità di ricostruire criteri, passaggi e responsabilità. Un archivio enorme, privo di una struttura comprensibile, può soddisfare un obbligo formale senza consentire un controllo effettivo.',110),
('C1','it-c1-s-04','Le procedure standard aumentano la coerenza e riducono l’arbitrarietà, ma devono lasciare spazio a eccezioni motivate. La difficoltà consiste nel distinguere una deroga giustificata da un trattamento di favore, documentando in modo verificabile le ragioni della decisione.',110),
('C2','it-c2-s-01','Una trasparenza soltanto apparente può nascondere le informazioni decisive sotto una massa di dettagli secondari. In tal modo l’istituzione mostra di aver aperto i propri archivi, ma rende più difficile comprendere quali criteri abbiano realmente determinato la scelta e chi ne debba rispondere.',125),
('C2','it-c2-s-02','La riforma corregge alcuni difetti evidenti, ma resta da dimostrare che modifichi gli incentivi che continuano a generare il problema. Se premi, sanzioni e obiettivi rimangono invariati, gli operatori possono adattare il comportamento alla nuova regola senza abbandonare la logica precedente.',125),
('C2','it-c2-s-03','Una regola formalmente uguale può produrre effetti molto diversi su persone che partono da condizioni differenti. Per questo uguaglianza e giustizia non coincidono sempre: valutare la neutralità di una misura richiede di osservare non soltanto il testo, ma anche risorse, vincoli e conseguenze concrete.',125),
('C2','it-c2-s-04','Il compromesso permette di agire senza un accordo completo, ma perde valore quando serve soltanto a nascondere obiettivi incompatibili. Una formula volutamente ambigua può facilitare l’intesa iniziale e, nello stesso tempo, rinviare il conflitto al momento dell’attuazione, quando i costi diventano più difficili da gestire.',125)]
keepS=[x for x in speaking['questions'] if x['level'] in {'A1','A2'}]
# remove exact duplicate with listening
for x in keepS:
    if x['id']=='it-a1-s-03': x['passage']='Vorrei prenotare un tavolo tranquillo per due persone, possibilmente vicino alla finestra.'
speaking['questions']=keepS+[{'id':i,'level':l,'skill':'speaking','prompt':'Leggi il testo ad alta voce. Presta attenzione a ritmo, accenti, doppie consonanti e collegamenti fra le parole.','passage':t,'maxDurationSec':d} for l,i,t,d in S]
speaking['version']='4.1.0-professional-direct'; speaking['questionCount']=28

save('it.json',main); save('it-listening.json',listening); save('it-speaking.json',speaking)
print('Italian v4.1 built:',len(main['questions']),len(listening['questions']),len(speaking['questions']))
